Add mapview
CM20314-Group-2/client pull request #5
Opened 2022-02-25 16:17 UTC by emilyforrest123

Populating the map with pins using the database.

2022-02-25 18:35 UTC, bridges-wood requested changes
Great first attempt! A couple of minor stylistic changes and this'll be ready to go. 👍

2022-02-25 18:35 UTC, bridges-wood commented on src/components/MapView.tsx
> +const ExampleLocations = [ExampleLocationOne, ExampleLocationTwo, ExampleLocationThree]
These can probably be removed now

2022-02-25 18:35 UTC, bridges-wood commented on src/components/MapView.tsx
> +const GetCoordinates = gql `
Please put this in `SHOUTING_SNAKE_CASE`

2022-02-25 18:35 UTC, bridges-wood commented on src/components/MapView.tsx
> +      </Marker>)
To keep code style consistent, it would be good to embed this map in the main body of the return

2022-02-25 18:35 UTC, bridges-wood commented on src/components/MapView.tsx
> +      </Map> :null}
It might be good to add some kind of error message to the user here

2022-02-25 18:35 UTC, bridges-wood commented on src/components/Pin.tsx
> +  // if the rating is > 66 then the pin will be green, between 33 and 66 the pin will be yellow, and red if < 33
This seems a bit redundant

2022-02-25 18:35 UTC, bridges-wood commented on src/components/Pin.tsx
> +  const colour = rating > 33 ? rating > 66 ? ['#1ea853', '#188441'] : ['#bed62e', '#a8bd29'] : ['#e2382d', '#842b18']
It would be good to extract these to a common location so that they can be reused.

2022-02-25 18:35 UTC, bridges-wood commented on src/components/Pin.tsx
> +  const colour = rating > 33 ? rating > 66 ? ['#1ea853', '#188441'] : ['#bed62e', '#a8bd29'] : ['#e2382d', '#842b18']
It would also be better to define these colour pairs as an object, rather than as an array. It would make the use of each colour clearer

2022-02-27 13:25 UTC, emilyforrest123 commented on src/components/Pin.tsx
> +  // if the rating is > 66 then the pin will be green, between 33 and 66 the pin will be yellow, and red if < 33
This is Camerons work

2022-02-28 14:30 UTC, bridges-wood requested changes
Two small things.

2022-02-28 14:30 UTC, bridges-wood commented on app.config.ts
> +      serverAddress: 'http://d477-2a01-4c8-481-b8aa-e4dd-5cdb-35a4-b97d.ngrok.io'
Please revert this file

2022-02-28 14:30 UTC, bridges-wood commented on src/components/MapView.tsx
> +  console.log('data', data)
Remove these logs

2022-02-28 14:32 UTC, bridges-wood approved these changes
Nice

2022-03-01 11:13 UTC, closed without merging